---
- name: restart pulsecheck app
  shell: |
    pkill -f gunicorn >/dev/null 2>&1 || true

    export DB_HOST={{ hostvars[groups['db'][0]]['ansible_host'] }}
    export DB_NAME=pulsecheck
    export DB_USER=pulsecheck_app
    export DB_PASSWORD='PulseCheckApp2024!'

    cd {{ app_dir }}

    nohup {{ app_dir }}/venv/bin/gunicorn \
      --workers {{ gunicorn_workers }} \
      --bind 0.0.0.0:{{ app_port }} \
      app:app >/tmp/pulsecheck.log 2>&1 &
  args:
    executable: /bin/bash
  async: 30
  poll: 0
