FROM ubuntu:24.04

ENV container=docker

RUN apt-get update && \
    apt-get install -y \
    systemd \
    systemd-sysv \
    openssh-server \
    sudo \
    python3 \
    python3-pip \
    python3-venv \
    postgresql-client \
    iproute2 && \
    apt-get clean

RUN mkdir /var/run/sshd && \
    useradd -m -s /bin/bash devops && \
    echo "devops:devops" | chpasswd && \
    usermod -aG sudo devops && \
    echo "devops ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

STOPSIGNAL SIGRTMIN+3

CMD ["/sbin/init"]
